[build]
  command = "next build"               # Comando per costruire l'app
  publish = ".next"                     # Directory di pubblicazione per Next.js
  functions = "netlify/functions"       # Percorso delle funzioni Netlify
  environment = { PYTHON_VERSION = "" }

## Configurazione del dominio
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

## Variabili d'ambiente per il contesto di produzione
[context.production.environment]
  NODE_VERSION = "18"                  # Imposta la versione 18 di Node.js

