[build]
  command = "next build"                # Comando per costruire l'app
  publish = ".next"                      # Directory di pubblicazione per Next.js
  functions = "netlify/functions"        # Percorso delle funzioni Netlify

  ## Redirects per SPA (facoltativo)
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html" 
  #  status = 200

  ## Impostazioni per Netlify Dev (facoltativo)
  #[dev]
  #  command = "yarn start"              # Comando per avviare il server di sviluppo
  #  port = 3000                          # Porta su cui ascoltare il server di sviluppo
  #  publish = "dist"                    # Cartella con il contenuto statico per il file _redirect

## Configurazione del dominio
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
